version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  client-chevoska:
    # image: chevoska/testapp:client2
    build: .
    platform: linux/amd64
    container_name: client
    ports:
      - '4202:80'

