version: '3.5'

volumes:
  db-volumes:
    driver: local
  cache:

services:
  db:
    image: mysql
    container_name: mysql-server
    restart: always
    ports:
     - 3307:3307
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_TCP_PORT: 3307
    volumes:
    - db-volumes:/var/lib/mysql
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  cache:
    image: redis
    container_name: cache-server
    restart: always
    ports:
      - 0.0.0.0:6379:6379
    volumes:
      - cache:/data

  backend:
   # image: chevoska/testapp:server2
    build: ./server
    container_name: server
    depends_on:
      - cache
      - db
    ports:
      - 0.0.0.0:3001:3001
    volumes:
      - /var/invent/uploads:/usr/src/app/public/uploads
    environment:
      - HOST=0.0.0.0
      - PORT=3001
      - NODE_ENV=development

      - TYPEORM_HOST=db
      - TYPEORM_PORT=3307
      - CUSTOM_HOST=http://168.119.62.93

      - REDIS_CLUSTER_MODE=false
      - REDIS_KEY_PREFIX=INVENT_
      - REDIS_CONNECTION_STRING=cache:6379

      - ALLOW_CORS=true
      - ACCESS_CONTROL_ALLOW_ORIGIN=http://168.119.62.93:4202,http://168.119.62.93
      - SESSION_SECURE=false # only for local, use `true` if start for production (https)
